#!/usr/bin/env node

// Debug script to check exact SQL being generated by Drizzle
import { drizzle } from 'drizzle-orm/postgres-js';
import postgres from 'postgres';
import { organizations } from '../shared/schema.ts';

const connectionString = process.env.DATABASE_URL;
const sql = postgres(connectionString);
const db = drizzle(sql, { logger: true }); // Enable logging

async function testInsert() {
  try {
    console.log('Testing organizations table insert...');
    
    const testData = {
      name: 'SQL Debug Test',
      is_business: false
    };
    
    console.log('Data to insert:', testData);
    
    const result = await db
      .insert(organizations)
      .values(testData)
      .returning();
    
    console.log('Insert successful:', result[0]);
    
  } catch (error) {
    console.error('Insert failed:', {
      message: error.message,
      code: error.code,
      detail: error.detail,
      hint: error.hint
    });
  } finally {
    await sql.end();
  }
}

testInsert();